### ISSUE TITLE
Figured you might want a hand

### ISSUE THREAD

**Issue by ObadiahCrowe** [cyanicdev/daymap-client#2]
Hey, just stumbled upon this. I used to go to the same school as you guys and worked on a very similar project which combined Daymap, Moodle, and Google Classroom under the one interface. Feel free to have a look around, it may help you :)

https://github.com/ObadiahCrowe/Stirling-v3
https://github.com/ObadiahCrowe/Stirling-v4

**Comment by javadhamidi** [comment]
thanks man, so cool to hear from you!
